FROM keymetrics/pm2:16-alpine
WORKDIR /src/app

COPY package*.json ./
RUN npm install 

COPY . .

ENV PORT $PORT
ENV HOST $HOST
ENV USER $USER
ENV PASSWORD $PASSWORD
ENV DATABASE $DATABASE
ENV EASYPAISAMERCHANTCREDENTIALS $EASYPAISAMERCHANTCREDENTIALS
ENV EPMASTOREID $EPMASTOREID
ENV EPQRSTOREID $EPQRSTOREID
ENV PQRTRANSACTIONPOINTNO $PQRTRANSACTIONPOINTNO
ENV NOTIFICATIONEMAIL $NOTIFICATIONEMAIL

EXPOSE 2000

ENTRYPOINT [ "pm2-runtime", "start", "index.js" ]
